### ISSUE TITLE
pull delimiter=null still has structure

### ISSUE THREAD

**Issue by wfjsw** [tolgee/tolgee-cli#89]
Tolgee CLI 2.0.3 + Tolgee Platform 3.64.8. 
Seems to be a regression of #57 

Config: 
```
$schema: "https://tolgee.io/cli-schema.json"
projectId: 20
delimiter: null
format: JSON_TOLGEE
push: 
  files:
    - path: "./StableDiffusionWebUILauncher/Localizations/Bundled/zh-Hans.json"
      language: "zh-Hans"
      forceMode: OVERRIDE
      convertPlaceholdersToIcu: true
pull:
  path: "./StableDiffusionWebUILauncher/Localizations/Bundled"
  state: 
    - REVIEWED
  emptyDir: false
```

![image](https://github.com/tolgee/tolgee-cli/assets/2220320/fde53d3f-5788-4911-8844-86085de077f7)

**Comment by stepan662** [comment]
Yes, seems like the whole `delimiter` option was somehow broken and there was no test for it, so I've added one and it should be fixed in the PR.

**Comment by wfjsw** [comment]
I can reproduce this issue still with above settings

![image](https://github.com/tolgee/tolgee-cli/assets/2220320/442739f2-6cb2-46e1-ad3e-dc8e8c9bae8e)

Even if I change `delimiter` to `''`

![image](https://github.com/tolgee/tolgee-cli/assets/2220320/532b0fa3-2704-4482-a5fa-a30da502b64c)

However it is gone if I use `-d ''`

![image](https://github.com/tolgee/tolgee-cli/assets/2220320/77e1d92b-b44c-4908-b414-d36bab395308)

**Comment by cyyynthia** [comment]
It appears delimiter is documented as a global property but this is a mistake. In CLIv2 it's `pull.delimiter`, so your yaml should look something like this:
```yaml
pull:
  delimiter: null
```

**Comment by stepan662** [comment]
Ah, I'll fix it in the docs.

**Comment by stepan662** [comment]
https://github.com/tolgee/documentation/pull/615
